############################################################
#
# web访问端口号  约定：8033
#
############################################################
server:
  port: 8033
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 106.52.36.53
    port: 6379
    password: 123456
  data:
    elasticsearch:
      cluster-name: es6
      # 9300是spring的端口配置。
      cluster-nodes: 106.52.36.53:9300

